### ISSUE TITLE
一运行就报错了

### ISSUE THREAD

**Issue by aojianwu** [RemoteDebug/remotedebug-ios-webkit-adapter#112]
remotedebug-ios-webkit-adapter is listening on port 9000
iosAdapter.getTargets
undefined:1
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request.request [as _callback] (C:\Users\xxx\AppData\Roaming\npm\n
ode_modules\remotedebug-ios-webkit-adapter\out\adapters\iosAdapter.js:44:38)
    at Request.self.callback (C:\Users\xxx\AppData\Roaming\npm\node_modul
es\remotedebug-ios-webkit-adapter\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\xxx\AppData\Roaming\npm\node_modules
\remotedebug-ios-webkit-adapter\node_modules\request\request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\xxx\AppData\Roaming\npm\node
_modules\remotedebug-ios-webkit-adapter\node_modules\request\request.js:1083:12)

    at Object.onceWrapper (events.js:313:30)

**Comment by Jack-Works** [comment]
try to remove the $http_proxy env

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
