### ISSUE TITLE
help!! SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by yarnbyte** [RemoteDebug/remotedebug-ios-webkit-adapter#132]
remotedebug-ios-webkit-adapter is listening on port 9000
iosAdapter.getTargets
undefined:1
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request.request [as _callback] (/usr/local/lib/node_modules/remotedebug-ios-webkit-adapter/out/adapters/iosAdapter.js:44:38)
    at Request.self.callback (/usr/local/lib/node_modules/remotedebug-ios-webkit-adapter/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/remotedebug-ios-webkit-adapter/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/remotedebug-ios-webkit-adapter/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)

----------------------------------------
mac book pro 2018
os: 10.14.3

**Comment by antimatter96** [comment]
@plat10510 did you find the problem ?

**Comment by Geczy** [comment]
Same issue ...

**Comment by NicolasVargas** [comment]
Hi @antimatter96 , @Geczy & @plat10510 ,

I solved it by adding "127.0.0.1" to NO_PROXY environment variable

**Comment by RealTadango** [comment]
I have the same issue. What could be causing this?

**Comment by jimpdx** [comment]
Same problem here. I tried the environment variable suggested by @NicolasVargas but still not working :/

**Comment by FirefighterBlu3** [comment]
normally means you're getting HTML instead of JSON
