### ISSUE TITLE
Windows 10 build error

### ISSUE THREAD

**Issue by oytunistrator** [RemoteDebug/remotedebug-ios-webkit-adapter#163]
```
npm start

> remotedebug-ios-webkit-adapter@0.3.2 start D:\Workspace\npm\remotedebug-ios-webkit-adapter
> gulp build && node out/index.js

[18:47:21] Using gulpfile D:\Workspace\npm\remotedebug-ios-webkit-adapter\gulpfile.js
[18:47:21] Starting 'build'...
src\server.ts(47,41): error TS2339: Property 'port' does not exist on type 'string | AddressInfo'.
  Property 'port' does not exist on type 'string'.
[18:47:23] TypeScript: 1 semantic error
[18:47:23] TypeScript: emit succeeded (with errors)
[18:47:23] Finished 'build' after 2.79 s
D:\Workspace\npm\remotedebug-ios-webkit-adapter\node_modules\depd\index.js:399
    throw new TypeError('argument fn must be a function')
    ^

TypeError: argument fn must be a function
    at Function.wrapfunction [as function] (D:\Workspace\npm\remotedebug-ios-webkit-adapter\node_modules\depd\index.js:399:11)
    at populateConstructorExports (D:\Workspace\npm\remotedebug-ios-webkit-adapter\node_modules\http-errors\index.js:264:45)
    at Object.<anonymous> (D:\Workspace\npm\remotedebug-ios-webkit-adapter\node_modules\http-errors\index.js:30:1)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (D:\Workspace\npm\remotedebug-ios-webkit-adapter\node_modules\send\index.js:15:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! remotedebug-ios-webkit-adapter@0.3.2 start: `gulp build && node out/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the remotedebug-ios-webkit-adapter@0.3.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tedar\AppData\Roaming\npm-cache\_logs\2019-08-02T15_47_24_254Z-debug.log
```

**Comment by auchenberg** [comment]
Closing as build seem to be passing now.
