### ISSUE TITLE
run remotedebug-ios-webkit-adpater get error

### ISSUE THREAD

**Issue by lemchen** [RemoteDebug/remotedebug-ios-webkit-adapter#198]
`PS C:\Users\> remotedebug_ios_webkit_adapter --port=9000
remotedebug-ios-webkit-adapter is listening on port 9000
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Request._callback (C:\Users\scoop\persist\nodejs\bin\node_modules\remotedebug-ios-webkit-adapter\out\adapters\iosAdapter.js:44:38)
    at Request.self.callback (C:\Users\scoop\persist\nodejs\bin\node_modules\remotedebug-ios-webkit-adapter\node_modules\_request@2.88.2@request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (C:\Users\scoop\persist\nodejs\bin\node_modules\remotedebug-ios-webkit-adapter\node_modules\_request@2.88.2@request\request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (C:\Users\scoop\persist\nodejs\bin\node_modules\remotedebug-ios-webkit-adapter\node_modules\_request@2.88.2@request\request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1224:12)`

can anyone here help?

**Comment by lemchen** [comment]
https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/182#issue-561890648
the same problem
