### ISSUE TITLE
Remote debug for iOS devices not working on chrome.

### ISSUE THREAD

**Issue by virajphadte84** [RemoteDebug/remotedebug-ios-webkit-adapter#203]
Not able to inspect webkit applications running iPad via remote debug using chrome as inspecting tool  . Earlier they were working fine
ios version - 12.3.1
windows - 10
chrome version - 85

**Comment by ShaCP** [comment]
I'm not seeing the device either. It used to work before.

**Comment by Lindsay-Needs-Sleep** [comment]
I swore it was working for me for iOS 9, then the next day it would detect the device, but the inspector window would be empty.

After closing iTunes, re-opening it, unplugging+replugging, starting and stopping remotedebug, and renaming my ipad, it magically started working again.

Glad to know I wasn't crazy.  Not sure which part of that actually made it work.

I did get this error the on the attempt to inspect just before it started working:  
```
remotedebug-ios-webkit-adapter is listening on port 9000
Error: Unexpected server response: 404
    at ClientRequest.<anonymous> (C:\Users\meee\AppData\Roaming\npm\node_modules\remotedebug-ios-webkit-adapter\node_modules\ws\lib\websocket.js:576:7)
    at ClientRequest.emit (events.js:210:5)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
    at Socket.socketOnData (_http_client.js:456:22)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)
```

**Comment by kumail-raza** [comment]
time waisted ! not working for chrome on ios.

**Comment by auchenberg** [comment]
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.
