### ISSUE TITLE
Does not work with chrome

### ISSUE THREAD

**Issue by salos1982** [RemoteDebug/remotedebug-ios-webkit-adapter#43]
I need to profile  mobile ios device but I cannot. There is log
:\Users\ssolozhentsev>remotedebug_ios_webkit_adapter --port=9000
adapter.start
remotedebug-ios-webkit-adapter is listening on port 9000
New websocket connection to /devtools/page/1
C:\Users\ssolozhentsev\AppData\Roaming\npm\node_modules\remotedebug-ios-webkit-adapter\out\adapters\iosAdapter.js:90
            var version = target.data.metadata.version;
                                ^

TypeError: Cannot read property 'data' of null
    at IOSAdapter.connectTo (C:\Users\ssolozhentsev\AppData\Roaming\npm\node_modules\remotedebug-ios-webkit-adapter\out\adapters\iosAdapter.js:90:33)
    at ProxyServer.onWSSConnection (C:\Users\ssolozhentsev\AppData\Roaming\npm\node_modules\remotedebug-ios-webkit-adapter\out\server.js:97:23)
    at WebSocketServer.<anonymous> (C:\Users\ssolozhentsev\AppData\Roaming\npm\node_modules\remotedebug-ios-webkit-adapter\out\server.js:34:64)
    at emitOne (events.js:77:13)
    at WebSocketServer.emit (events.js:169:7)
    at C:\Users\ssolozhentsev\AppData\Roaming\npm\node_modules\remotedebug-ios-webkit-adapter\node_modules\ws\lib\WebSocketServer.js:91:14
    at completeHybiUpgrade2 (C:\Users\ssolozhentsev\AppData\Roaming\npm\node_modules\remotedebug-ios-webkit-adapter\node_modules\ws\lib\WebSocketServer.js:284:5)
    at completeHybiUpgrade1 (C:\Users\ssolozhentsev\AppData\Roaming\npm\node_modules\remotedebug-ios-webkit-adapter\node_modules\ws\lib\WebSocketServer.js:309:13)
    at WebSocketServer.handleHybiUpgrade (C:\Users\ssolozhentsev\AppData\Roaming\npm\node_modules\remotedebug-ios-webkit-adapter\node_modules\ws\lib\WebSocketServer.js:337:3)
    at WebSocketServer.handleUpgrade (C:\Users\ssolozhentsev\AppData\Roaming\npm\node_modules\remotedebug-ios-webkit-adapter\node_modules\ws\lib\WebSocketServer.js:173:26)

**Comment by auchenberg** [comment]
@salos1982 Can you try to pull master and see if the issue has been resolved for you?

**Comment by salos1982** [comment]
sorry currently it is not possible

**Comment by iFwu** [comment]
I know where the problem is. Turn off `Discover USB devices` or just turn the `Port Forwarding` off  in Chrome Inspect Tool (Chrome://inspect) and everything is ok.

Besides, I download the master and run `npm install` and `npm start`, and the TS tests may seem wrong. The logs below: 

```
> remotedebug-ios-webkit-adapter@0.1.4 start /Users/blanu/Downloads/remotedebug-ios-webkit-adapter-master
> gulp build && node out/index.js

[16:18:57] Using gulpfile ~/Downloads/remotedebug-ios-webkit-adapter-master/gulpfile.js
[16:18:57] Starting 'build'...
test/protocols/target.test.ts(26,1): error TS2304: Cannot find name 'suite'.
test/protocols/target.test.ts(53,5): error TS2304: Cannot find name 'setup'.
test/protocols/target.test.ts(72,5): error TS2304: Cannot find name 'teardown'.
test/protocols/target.test.ts(82,5): error TS2304: Cannot find name 'suite'.
test/protocols/target.test.ts(83,9): error TS2304: Cannot find name 'test'.
test/protocols/target.test.ts(92,9): error TS2304: Cannot find name 'test'.
test/protocols/target.test.ts(121,5): error TS2304: Cannot find name 'suite'.
test/protocols/target.test.ts(122,9): error TS2304: Cannot find name 'setup'.
test/protocols/target.test.ts(126,9): error TS2304: Cannot find name 'test'.
test/protocols/target.test.ts(146,9): error TS2304: Cannot find name 'test'.
test/protocols/target.test.ts(167,5): error TS2304: Cannot find name 'suite'.
test/protocols/target.test.ts(168,9): error TS2304: Cannot find name 'setup'.
test/protocols/target.test.ts(172,9): error TS2304: Cannot find name 'test'.
test/protocols/target.test.ts(193,5): error TS2304: Cannot find name 'suite'.
test/protocols/target.test.ts(194,9): error TS2304: Cannot find name 'setup'.
test/protocols/target.test.ts(198,9): error TS2304: Cannot find name 'test'.
test/protocols/target.test.ts(219,5): error TS2304: Cannot find name 'suite'.
test/protocols/target.test.ts(220,9): error TS2304: Cannot find name 'setup'.
test/protocols/target.test.ts(224,9): error TS2304: Cannot find name 'test'.
test/protocols/target.test.ts(258,9): error TS2304: Cannot find name 'test'.
test/protocols/target.test.ts(283,5): error TS2304: Cannot find name 'suite'.
test/protocols/target.test.ts(284,9): error TS2304: Cannot find name 'setup'.
test/protocols/target.test.ts(288,9): error TS2304: Cannot find name 'test'.
test/protocols/target.test.ts(310,9): error TS2304: Cannot find name 'test'.
test/protocols/target.test.ts(332,9): error TS2304: Cannot find name 'test'.
test/protocols/target.test.ts(363,5): error TS2304: Cannot find name 'suite'.
test/protocols/target.test.ts(364,9): error TS2304: Cannot find name 'setup'.
test/protocols/target.test.ts(368,9): error TS2304: Cannot find name 'test'.
test/protocols/target.test.ts(396,5): error TS2304: Cannot find name 'suite'.
test/protocols/target.test.ts(397,9): error TS2304: Cannot find name 'setup'.
test/protocols/target.test.ts(401,9): error TS2304: Cannot find name 'test'.
[16:18:59] TypeScript: 31 semantic errors
[16:18:59] TypeScript: emit succeeded (with errors)
[16:18:59] Finished 'build' after 1.31 s
remotedebug-ios-webkit-adapter is listening on port 9000
iosAdapter.getTargets
New websocket connection to /devtools/browser
/Users/blanu/Downloads/remotedebug-ios-webkit-adapter-master/out/adapters/iosAdapter.js:92
            const version = target.data.metadata.version;
                                  ^

TypeError: Cannot read property 'data' of null
    at IOSAdapter.connectTo (/Users/blanu/Downloads/remotedebug-ios-webkit-adapter-master/out/adapters/iosAdapter.js:92:35)
    at ProxyServer.onWSSConnection (/Users/blanu/Downloads/remotedebug-ios-webkit-adapter-master/out/server.js:116:23)
    at WebSocketServer._wss.on (/Users/blanu/Downloads/remotedebug-ios-webkit-adapter-master/out/server.js:36:52)
    at emitOne (events.js:96:13)
    at WebSocketServer.emit (events.js:188:7)
    at /Users/blanu/Downloads/remotedebug-ios-webkit-adapter-master/node_modules/ws/lib/WebSocketServer.js:91:14
    at completeHybiUpgrade2 (/Users/blanu/Downloads/remotedebug-ios-webkit-adapter-master/node_modules/ws/lib/WebSocketServer.js:284:5)
    at completeHybiUpgrade1 (/Users/blanu/Downloads/remotedebug-ios-webkit-adapter-master/node_modules/ws/lib/WebSocketServer.js:309:13)
    at WebSocketServer.handleHybiUpgrade (/Users/blanu/Downloads/remotedebug-ios-webkit-adapter-master/node_modules/ws/lib/WebSocketServer.js:337:3)
    at WebSocketServer.handleUpgrade (/Users/blanu/Downloads/remotedebug-ios-webkit-adapter-master/node_modules/ws/lib/WebSocketServer.js:173:26)

npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/blanu/n/bin/node" "/Users/blanu/n/bin/npm" "start"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! remotedebug-ios-webkit-adapter@0.1.4 start: `gulp build && node out/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the remotedebug-ios-webkit-adapter@0.1.4 start script 'gulp build && node out/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the remotedebug-ios-webkit-adapter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build && node out/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs remotedebug-ios-webkit-adapter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls remotedebug-ios-webkit-adapter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/blanu/Downloads/remotedebug-ios-webkit-adapter-master/npm-debug.log
```

**Comment by auchenberg** [comment]
@xekri Looks like you have a tool that's trying to connect to the WebSocket connection as "/devtools/browser".

Does this error only when you have USB Discovery enabled?

**Comment by iso-aal** [comment]
Hi, 
I also have the same problem , I have tried to turn off Discover USB devices in DevTools but it didn't help.. 
the error which I am getting : 
BTW I have Node v6.9.5 and NPM -v4.3

remotedebug-ios-webkit-adapter is listening on port 9000
iosAdapter.getTargets
undefined:1
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
^

SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at Request.request [as _callback] (C:\Users\aal\AppData\Roaming\npm\node_modules\remotedebug-ios-webkit-adapter\out\adapters\iosAdapter.js:44:38)
    at Request.self.callback (C:\Users\aal\AppData\Roaming\npm\node_modules\remotedebug-ios-webkit-adapter\node_modules\request\request.js:185:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\aal\AppData\Roaming\npm\node_modules\remotedebug-ios-webkit-adapter\node_modules\request\request.js:1157:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\aal\AppData\Roaming\npm\node_modules\remotedebug-ios-webkit-adapter\node_modules\request\request.js:1079:12)
    at IncomingMessage.g (events.js:291:16)

**Comment by pixlab** [comment]
I've the same error....do you have resolved it?

thanks

**Comment by stefan-reloyalty** [comment]
In case someone else ends here:
I saw the solution here:
https://www.bountysource.com/issues/88231335-error-unexpected-end-of-json-input
The key thing is to use port 9222
