### ISSUE TITLE
missing dependency: `debug`

### ISSUE THREAD

**Issue by hirokith** [RemoteDebug/remotedebug-ios-webkit-adapter#58]
```
module.js:471
    throw err;
    ^

Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/remotedebug-ios-webkit-adapter/out/logger.js:6:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by auchenberg** [comment]
`debug` is a devDependency, https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/blob/master/package.json#L28

When do you get this?

**Comment by hirokith** [comment]
I just followed the install instructions: https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter#getting-started and ran `remotedebug_ios_webkit_adapter --port=9000` at the end. I figured out to install `debug` globally and solved the issue, however it seems that the `debug` module is required in runtime source code? https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/blob/master/src/logger.ts#L5

**Comment by auchenberg** [comment]
Ah, dang. I'll get that fixed.

**Comment by auchenberg** [comment]
Version 0.1.9 published, https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/releases/tag/v0.1.9

Try to update and let me know how it works.

**Comment by hirokith** [comment]
OK it worked now, thanks!~
