### ISSUE TITLE
chrome://inspect/#devices   selcect url inspect , it could not run 

### ISSUE THREAD

**Issue by linwenbang** [RemoteDebug/remotedebug-ios-webkit-adapter#83]
`
New websocket connection to /ios_5a2398353483d9eb053932b8bec738cefed62b08/PID:2359
Existing target found for id PID:2359
Error: unexpected server response (404)
    at ClientRequest.response (/usr/local/lib/node_modules/remotedebug-ios-webkit-adapter/node_modules/ws/lib/WebSocket.js:719:15)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:522:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at Socket.socketOnData (_http_client.js:411:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
Socket is closed
`

**Comment by auchenberg** [comment]
@linwenbang Please provide more details on your OS, IOS version, device, etc..

**Comment by auchenberg** [comment]
Closing due to in activity.
